State, Reducer and Action
Ibnballo1/bookstore pull request #2
Opened 2022-08-18 21:15 UTC by Ibnballo1

I implemented the following in this PR;

- I added Redux Toolkit(npm install react-redux @reduxjs/toolkit).
- I added folders and subfolders to the Redux folder
- I wrote the book's action and reducers
- I also wrote the categories action and reducer
- and then, I created a store for the state

2022-08-18 21:59 UTC, AmaduKamara requested changes
# Status: Required Changes ♻️♻️♻️ 

Hi @Ibnballo1,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✅ You used Gitflow correctly
✅ No linter error
✅ Good commit messages

## Required Changes ♻️
_Check the comments under the review._

- [ ] Kindly work on the app routes as nothing is being loaded to the screen. Please fix that 👍 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-08-18 21:59 UTC, AmaduKamara commented on src/redux/books/books.js
> +// }
- [ ] Kindly remove all commented code that is of no use to your codebase. Comments are meant only for a feature or details of a code feature as documentation of your code. But having a code written and commented on makes your code dirty. Please remove it so your codebase looks professional and clean 👍

2022-08-18 21:59 UTC, AmaduKamara commented on src/redux/books/books.js
> +const REMOVE_BOOK = 'REMOVE_BOOK';
- [ ] It would be nice if you follow the Duck pattern in naming your actions as it is part of the requirements.

HINTS:
`const ADD_BOOK = bookstore/books/ADD_BOOK`

2022-08-18 21:59 UTC, AmaduKamara commented on src/redux/categories/categories.js
> +const STATUS = 'STATUS';
- [ ] It would be nice if you follow the Duck pattern in naming your action as it is part of the requirements.

HINT:
`const STATUS = bookstore/categories/STATUS`

2022-08-18 21:59 UTC, AmaduKamara commented on src/redux/categories/categories.js
> +      return ('Status updated');
- [ ] Kindly return the string ` "Under construction" ` when checking the status. You are required to return that string and not the one you did. Please change that 👍

2022-08-19 00:45 UTC, mateo951 approved these changes
### Hi @Ibnballo1, 

Well done making all the necessary changes 🚀 Your project is complete!  There is nothing else to say other than... it's time to merge it 💣 
### Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-19 00:45 UTC, mateo951 commented on src/redux/books/books.js
> +
Addressed 🔥 Comments were removed ✔

2022-08-19 00:45 UTC, mateo951 commented on src/redux/books/books.js
> +const REMOVE_BOOK = 'bookstore/books/REMOVE_BOOK';
Addressed 🚀 Your action types now follow the duck pattern 🤓

2022-08-19 00:45 UTC, mateo951 commented on src/redux/categories/categories.js
> +const STATUS = 'bookstore/categories/STATUS';
Addressed 🚀 Your action type now follow the duck pattern 🤓

2022-08-19 00:45 UTC, mateo951 commented on src/redux/categories/categories.js
> +      return ('Under construction');
Nice!

2022-08-19 01:07 UTC, Ibnballo1 commented on src/redux/categories/categories.js
> +      return ('Under construction');
Really love your feeedback, Thanks @mateo951

2022-08-19 01:10 UTC, merged